### ISSUE TITLE
Import export feature? 

### ISSUE THREAD

**Issue by EdOverride** [XspeedPL/PhysicalButtonMod#3]
Would it be possible to make import/export method for some and/or all chains?

**Comment by XspeedPL** [comment]
Wouldn't be a problem. Why do you need it?

**Comment by EdOverride** [comment]
@xspeedpl I have multiple phones and I change/reinstall there OS more often than I would like to admit.. :D

It would just be an awesome feature to otherwise perfect xposed module, as I have found that, for some reason, titanium backup doesn't backup the settings correctly.

**Comment by XspeedPL** [comment]
Yes, Titanium Backup did not age well.

If it's just backing up and restoring, you can just store the shared preferences file somewhere in the meantime. You might need to use chmod and chown proper when restoring it though.

I will look into implementing the feature when I have time, it seems handy for sharing configurations with others, since this module has a few users now.

**Comment by EdOverride** [comment]
That would be an awesome feature, in my opinion, as I can't recommend this module enough.

This module is the ONLY reason why I have xposed installed on all my phones.

**Comment by XspeedPL** [comment]
Implemented in 4.3
